const projectList = [
    {
        id: 1,
        title: "Portfolio Website",
        category: "web",
        summary: "A web version of my Resume. This was made using vanilla HTML, CSS and Javascript.",
        link: "https://github.com/debroglie27/PortfolioWebsite",
    },
    {
        id: 2,
        title: "PDF Merger App (Tkinter Python)",
        category: "software",
        summary: "Created a GUI using Tkinter, Python to merge pdf files in noncontiguous manner.",
        link: "https://github.com/debroglie27/PDFMergerApp",
    },
    {
        id: 3,
        title: "PDF Merger App (Electron JS)",
        category: "software",
        summary: "Created a GUI using ElectronJS to merge pdf files in noncontiguous manner.",
        link: "https://github.com/debroglie27/PDFMergerApp",
    },
    {
        id: 4,
        title: "Currency Converter App",
        category: "software",
        summary: "Created a GUI using Tkinter, Python to convert one form of currency to another with the help of an API.",
        link: "https://github.com/debroglie27/CurrencyConverterApp",
    },
    {
        id: 5,
        title: "Ludo Game",
        category: "game",
        summary: "Created a well known board game using Python, Pygame.",
        link: "https://github.com/debroglie27/LudoGame",
    },
    {
        id: 6,
        title: "Address Database",
        category: "software",
        summary: "An app to store, retrive and maintain database having addresses. Created using Python, Tkinter sqlite3.",
        link: "https://github.com/debroglie27/AddressDatabase",
    },
    {
        id: 7,
        title: "Age Calculator App",
        category: "web",
        summary: "Created a web app, displaying age based on date of birth, with simple HTML, CSS and JS.",
        link: "https://github.com/debroglie27/AgeCalculatorApp",
    },
    {
        id: 8,
        title: "Factory Simulation",
        category: "software",
        summary: "An app to store, retrive and maintain database having factory related information. Created using Python, Tkinter sqlite3.",
        link: "https://github.com/debroglie27/FactorySimulation",
    },
    {
        id: 9,
        title: "BMI Calculator",
        category: "web",
        summary: "Created a web app, displaying BMI based on height and weight, with simple HTML, CSS and JS.",
        link: "https://github.com/debroglie27/BMICalculator",
    },
    {
        id: 10,
        title: "Paint App",
        category: "software",
        summary: "Created an app to make beautiful and mesmerizing paintings.",
        link: "https://github.com/debroglie27/PaintApp",
    },
    {
        id: 11,
        title: "Color Guesser",
        category: "web",
        summary: "Created a web game, to guess randomly generated colors, with simple HTML, CSS and JS.",
        link: "https://github.com/debroglie27/ColorGuesser",
    },
];

export {projectList};